(import (rnrs))
;;; I used this recursive approach in my lexing code base for Lox in GNU Guile
;;; it is all about iteration
(define (return x) x)
(define (markup? x)
  (or (char=? #\( x)
      (char=? #\) x)
      (char=? #\- x)
      (char=? #\. x)
      (char=? #\+ x)))
(define whitespace? char-whitespace?)
(define numeric? char-numeric?)
(define (valid-length? num) (= 10 (length num)))
(define (valid-number? nums)
  (if (char=? #\0 (car nums))
      (error "Invalid char" (car nums))
      (if (char=? #\1 (car nums))
       (valid-length? (cdr nums))
       (valid-length? nums))))

(define (validate num)
  (if (char=? #\1 (car num))
      (cdr num)
      (return num)))
;; runs after the validate code
(define (area-code nums)
  (if (char=? #\0 (car nums))
    (error "Invalid number" (car nums))
    (return nums)))
(define (exchange-code nums)
  (if (or (char=? #\1 (list-ref nums 3))
          (char=? #\0 (list-ref nums 3)))
    (error "invalid exchange code" #\1)
    (return nums)))
(define (doesnotstart nums)
  (if (char=? #\1 (car nums))
    (error "I hate this" #\1)
    (return nums)))

(define (inner nums)
  (if (null? nums)
      (return '())
      (cond ((numeric? (car nums))
             (cons (car nums)
              (inner (cdr nums))))
       ((or (whitespace? (car nums))
         (markup? (car nums)))
        (inner (cdr nums)))
       (else (error "Invalid character" (car nums))))))
(define (clean phone-number)
  (let* ((nums (string->list phone-number))
         (result (inner nums)))
    (if (valid-number? result)
     (list->string (doesnotstart (exchange-code (area-code (validate  result)))))
     (error "Invalid number" phone-number))))
